### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Johnsonk79** [HimbeersaftLP/HideCommands#1]
Hey! I love this plugin, it makes the server look much cleaner for the players, but is it possible to implement a feature for ops to still see hidden commands? or players with certain permission? Thanks a lot!

**Comment by HimbeersaftLP** [comment]
Sure, I'll add it to my todo list and let you know once I'm finished

**Comment by HimbeersaftLP** [comment]
Done

**Comment by HimbeersaftLP** [comment]
You can download the phar here: https://poggit.pmmp.io/ci/HimbeersaftLP/HideCommands/~

Let me know if it works for you.

The permission `hidecommands.unhide` allows a player to see all commands again (I made it default: false so you'll need to explicitly give it to the player).

**Comment by Johnsonk79** [comment]
Thanks!
