### ISSUE TITLE
Configuration error.

### ISSUE THREAD

**Issue by StefanFox4ik** [HimbeersaftLP/HideCommands#23]
When starting the server, it crashes because of the plugin.
The problem is in the config (I didn't even change it)

[11:57:28.166] [Server thread/CRITICAL]: ErrorException: "yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 17, column 16)" (EXCEPTION) in "pmsrc/src/plugin/PluginDescription" at line 90

PM4

**Comment by HimbeersaftLP** [comment]
The error coming from `PluginDescription` tells me PocketMine cannot parse the plugin.yml file, but that is inside the plugin.

I cannot reproduce this issue on PocketMine 4.0.6 and 2.0.0 of this plugin downloaded from Poggit.

@StefanFox4ik What exact version of PocketMine are you running and under which OS? Also of the plugin and where you got it from. Please also tell me if you made any modifications to either,

**Comment by HimbeersaftLP** [comment]
@StefanFox4ik Hello?
