### ISSUE TITLE
Single commands dont Work

### ISSUE THREAD

**Issue by QuiverlyRivalry** [HimbeersaftLP/HideCommands#3]
I have a command called "/k" when I kept it in the config (- "k") it doesn't show up on the commands players can only use.

**Comment by HimbeersaftLP** [comment]
Are you sure you are on blacklist mode?

**Comment by QuiverlyRivalry** [comment]
![image](https://user-images.githubusercontent.com/29443930/82759268-eaa9f300-9db1-11ea-94e8-4941fbd4de6e.png)

Yep. Here is my config. (/k) refers to the command which is not working. /k is properly registered and if player does /k it still works so I don't think its broken.

**Comment by QuiverlyRivalry** [comment]
Accidently closed it

**Comment by HimbeersaftLP** [comment]
Are you sure the command shows up without my plugin? Maybe it's a bug in Minecraft.

**Comment by QuiverlyRivalry** [comment]
Yep the command shows up without the plugin installed.

**Comment by HimbeersaftLP** [comment]
I'm 99% certain that this isn't a bug in my plugin (its code is so simple, there's almost no way a bug like this could arise). I will try making a test plugin with a single letter command tomorrow and see if that works.

**Comment by QuiverlyRivalry** [comment]
Yeah I was also confused, Ill double check to see if something is wrong on my part.

**Comment by HimbeersaftLP** [comment]
Just to make sure: k is the command's full name, not an alias, right?

**Comment by QuiverlyRivalry** [comment]
Ah yep that solved it thanks :D. /k was an alias of /kingdom; once I added /kingdom to the list it showed both /k and /kingdom. Thank you!

**Comment by HimbeersaftLP** [comment]
I should probably add that to the readme
