### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by DragonfireHD98** [HimbeersaftLP/HideCommands#30]
"Himbeer\HideCommands\Settings::__construct(): Argument #1 ($configData) must be of type array, bool given, called in /home/container/plugins/CommandEntfernerPerWorld/src/Himbeer/HideCommands/Main.php on line 32" (EXCEPTION) in "plugins/CommandEntfernerPerWorld/src/Himbeer/HideCommands/Settings" at line 21
--- Stack trace ---
  #0 plugins/CommandEntfernerPerWorld/src/Himbeer/HideCommands/Main(32): Himbeer\HideCommands\Settings->__construct(false)
  #1 pmsrc/src/plugin/PluginBase(119): Himbeer\HideCommands\Main->onEnable()
  #2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #3 pmsrc/src/Server(1407): pocketmine\plugin\PluginManager->enablePlugin(object Himbeer\HideCommands\Main#52635)
  #4 pmsrc/src/Server(1036): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#45253)
  #5 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(364): pocketmine\server()
  #7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by HimbeersaftLP** [comment]
@DragonfireHD98 Your config is probably malformed. Please show me your config.yml file.

**Comment by DragonfireHD98** [comment]
---
# HideCommands config file:

# Wichtiger Hinweis: Verwenden Sie immer die vollständigen Befehlsnamen, keine Aliase!
# Durch das Ausblenden eines Befehls werden auch alle seine Aliase ausgeblendet

# Zum Beispiel: „unban“ ist ein Alias von „pardon“
# um den Befehl „unban“ auszublenden,
# „pardon“ zur Blacklist hinzufügen

####################
# Default settings #
####################

# Diese Einstellungen gelten für alle Welten, die unten nicht unter „per World“ definiert sind.
Standard:
  # Der Modus kann entweder „Blacklist“ oder „Whitelist“ sein.
  # Im Whitelist-Modus werden nur die unten angegebenen Befehle angezeigt und alle anderen ausgeblendet
  # Im Blacklist-Modus werden die unten angegebenen Befehle ausgeblendet und alle anderen angezeigt
  mode: "blacklist"

  # List of commands to whitelist/blacklist (depending on the mode set above)

  commands: 
     - op
     #Beispiel - op #

######################
# Per world settings #
######################

# Diese Einstellungen überschreiben die Standardeinstellungen je nach Welt
# der Spieler ist dabei. Verwenden Sie den Ordnernamen der Welt als Index.

per-world:
   Sublobby:
     mode: "blacklist"
     commands:
       - "tagesbelohnung"

# Beispiel
#  Sublobby:
#    mode: "blacklist"
#    commands:
#     - "myplot"



# Config version, used internally
# Do not change this value!
version: 3
...

**Comment by DragonfireHD98** [comment]
@HimbeersaftLP

**Comment by HimbeersaftLP** [comment]
@DragonfireHD98 Du hast die Config in Google Translate gegeben und deshalb ist sie kaputt gegangen....
Wenn, dann darfst du nur die Kommentare übersetzen lassen (Zeilen, die mit "#" beginnen)

**Comment by HimbeersaftLP** [comment]
Wenn du Hilfe beim Konfigurieren brauchst, kannst du auf den in der README verlinkten Discord Chat gehen.
