### ISSUE TITLE
Commands per Permission

### ISSUE THREAD

**Issue by suerion** [HimbeersaftLP/HideCommands#4]
Could you add an option, do add all commands, what the groups has permissions set in pureperms or something?

It would be nice, if they could be set itself.

**Comment by HimbeersaftLP** [comment]
PocketMine already only shows commands that players have the permission to use.

**Comment by suerion** [comment]
Okey, but would your plugin show them all, when they are whitelisted? I had tested it, and all the plugin commands are shown without permission

**Comment by HimbeersaftLP** [comment]
They shouldn't be, are you sure?

**Comment by suerion** [comment]
i think, thats not right...

Picture from XBOX:
https://screenshotscontent-d3002.xboxlive.com/xuid-2535437606161822-private/18e8ad51-6a26-4100-a52e-ed105f36ddbb.PNG?sv=2015-12-11&sr=b&si=DefaultAccess&sig=zAXqQvQLffSKhpGQc%2Fekq6XmoN1bZRn6b8SM%2Fkwi5Yo%3D

`permissions:
      - essentialstp.command.bedsethome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.sign.spawn
      - essentialstp.command.sign.warp
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - myplot.claimplots.2
      - myplot.command.addhelper
      - myplot.command.auto
      - myplot.command.biome
      - myplot.command.biomes
      - myplot.command.claim
      - myplot.command.clear
      - myplot.command.denyplayer
      - myplot.command.dispose
      - myplot.command.done
      - myplot.command.generate
      - myplot.command.give
      - myplot.command.help
      - myplot.command.home
      - myplot.command.homes
      - myplot.command.info
      - myplot.command.list
      - myplot.command.middle
      - myplot.command.name
      - myplot.command.pvp
      - myplot.command.removehelper
      - myplot.command.undenyplayer
      - myplot.command.warp
      - pchat.coloredMessages
      - pocketmine.command.help
      - pocketmine.command.list
      - pocketmine.command.me
      - pocketmine.command.tell
      - pocketmine.command.transferserver
      - portalspe.portal.Minigames
      - skin.stealer
      - worldguard.enter.Plotwelt
      - worldguard.enter.global.Plotwelt
      - worldguard.leave.Plotwelt`

**Comment by HimbeersaftLP** [comment]
Do those commands not get shown when my plugin isn't installed?

**Comment by suerion** [comment]
I will try it, without your plugin

**Comment by suerion** [comment]
Okey, it was not your Plugin, sorry,

EasyCommand has a problem and show all Commands

**Comment by HimbeersaftLP** [comment]
No problem. As a workaround, if you don't want to patch that other plugin, you can remove these commands from the whitelist and give your admins the permission `hidecommands.unhide` so they can see all commands.
